# Generated by Django 3.0 on 2019-12-31 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instaphoto', '0002_auto_20191231_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Post',
        ),
    ]
