# Generated by Django 3.0 on 2020-01-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaphoto', '0003_auto_20191231_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
