# Generated by Django 3.0 on 2020-01-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaphoto', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
