# Generated by Django 3.0 on 2020-01-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaphoto', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
