# Generated by Django 3.0 on 2020-01-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaphoto', '0012_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
